### ISSUE TITLE
Make 'dev' branch docs available

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/docs#11]
Just throwing an idea.

I think it'd be very useful to have the 'dev' branch available through a subdomain like _[dev.vuetifyjs.com](dev.vuetifyjs.com)_, or something similar.

That way, whoever is working through the 'dev' branch or just helping the project, doesn't need to keep digging into the documentation source code to quickly access the framework docs.

Great work!

**Comment by prograhammer** [comment]
You can easily pull down the dev branch to your local machine and then `yarn install` and `yarn dev` to see it.
