### ISSUE TITLE
outside is null, app is null

### ISSUE THREAD

**Issue by marleybobby** [vuetifyjs/docs#113]
I want to include vuetify in an existing vue project. I successfully used v-tooltip. For testing purpose i copied the select and data from vuetify directly.  
I tried to use the Select component but I receive errors:

>  outside is null, app is null

The console showed me the errors here:
> outside.addEventListener('click', click, false);

and here
> app.insertBefore(_this.$refs.content, app.firstChild);

My component looks as following:  (Had to stripe out the opening tag, for what ever reason.)

`template lang="html">
div class="col s6">
            v-select
              label="Select"
              v-bind:items="states"
              v-model="e7"
              multiple
              chips
              hint="What are the target regions"
              persistent-hint
            >/v-select>
/div>
/template>`

`<script>

    import Vue from 'vue'
    import Vuetify from 'vuetify';

    Vue.use(Vuetify);

    export default{

        data(){
            return {
                e7: [],
                states: [
                    'Alabama','Alaska','American Samoa','Arizona',
                    'Arkansas','California','Colorado','Connecticut',
                    'Delaware','District of Columbia','Federated States of Micronesia',
                    'Florida','Georgia','Guam','Hawaii','Idaho',
                    'Illinois','Indiana','Iowa','Kansas','Kentucky',
                    'Louisiana','Maine','Marshall Islands','Maryland',
                    'Massachusetts','Michigan','Minnesota','Mississippi',
                    'Missouri','Montana','Nebraska','Nevada',
                    'New Hampshire','New Jersey','New Mexico','New York',
                    'North Carolina','North Dakota','Northern Mariana Islands','Ohio',
                    'Oklahoma','Oregon','Palau','Pennsylvania','Puerto Rico',
                    'Rhode Island','South Carolina','South Dakota','Tennessee',
                    'Texas','Utah','Vermont','Virgin Island','Virginia',
                    'Washington','West Virginia','Wisconsin','Wyoming'
                ]
            }
        }

    }
</script>`

What am I doing wrong?

EDIT:
Solved, forgot the v-app component, found the solution [https://github.com/vuetifyjs/vuetify/issues/402](url)

**Comment by johnleider** [comment]
Awesome!
