### ISSUE TITLE
Select component item-text and item-value with property path

### ISSUE THREAD

**Issue by smxsm** [vuetifyjs/docs#114]
Hi there, I am having problems setting item-text and item-value for select components if the property is "nested" in the items object, e.g.

<v-select
v-bind:items="bundle._bundleParts"
v-model="bundleparts"
label="Select"
item-text="_product.title.de"
item-value="_product._id"
autocomplete
>
</v-select>

If I output the values as text I can see them, e.g. with:

... div v-for="(row, key) in bundle._bundleParts" :key="key" value="true">
	{{ row.subProductQuantity }} x {{ row._product.title.de }}

But the select compoment doesn't "find" the values it seems and the option values are empty... any idea / hint? Thanks in advance!

**Comment by johnleider** [comment]
Wrong repository for this, but that was actually addressed in https://github.com/vuetifyjs/vuetify/pull/985
