### ISSUE TITLE
"v-select" selecting element doesn't work (Vuetify version 0.14.7)

### ISSUE THREAD

**Issue by kkkaspar** [vuetifyjs/docs#136]
Element "v-select" "selectItem" method is not executing.

Code I used:
`

<template>
<v-select
             v-bind:items="options"
             v-model="selectedOption"
></v-select>
</template>

<script>
  export default {
    data () {
      return {
        options: [
          {
            value: 0,
            text: 'TITLE'
          },
          {
            value: 1,
            text: 'ARTIST'
          }
        ],
        selectedOption: 0,
      }
    }
  }
</script>
`

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
