### ISSUE TITLE
v-edit-dialog in v-data-table not clickable when value is empty

### ISSUE THREAD

**Issue by chameleonlizzard** [vuetifyjs/docs#206]
when using a v-edit-dialog in a v-data-table and the value of the data-table cell is empty, it is not possible to click / open an editable cell. The width of v-menu that triggers the v-edit-dialog is `0px` and therefor not clickable.

**Comment by nekosaur** [comment]
Please open an issue on the vuetify repo instead. This is only for documentation related issues.
