### ISSUE TITLE
Fix for #172 breaks slots lists

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/docs#213]
Forms API at 73b58ac9526d8cc09bca1f47b644fce4ca946b3a:
![image](https://user-images.githubusercontent.com/16421948/30238548-7e8d9882-958c-11e7-8400-e5bd643003d8.png)

And at ccb2393e6a58764368a63b1bbf90635b994326a8:
![image](https://user-images.githubusercontent.com/16421948/30238564-a1afa350-958c-11e7-87f1-0bcd55d10f71.png)

Events and Props are not affected.

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/docs/commit/2c3a6465c780a19847f8637704c37da3d11d5d81
