### ISSUE TITLE
 Update for Chips with Selects

### ISSUE THREAD

**Issue by jameshhood** [vuetifyjs/docs#219]
After consulting with @johnleider and @jacekkarczmarczyk on discord, The docs/examples/chips/7.vue select example doesnt seem complete having the close tag in the chip but not be closable. @jacekkarczmarczyk provided a codepen to be able to close the chips and I recommend it be published with the documentation for a more full example. 
[CodePen](https://codepen.io/anon/pen/KXKmjR) Thanks!

**Comment by jacekkarczmarczyk** [comment]
Looks like it's working in the current docs (example 8)

**Comment by johnleider** [comment]
This was resolved with 0.15.7

**Comment by johnleider** [comment]
I've added your changes.
