### ISSUE TITLE
Add native form validation example that requires reference to the Vue instance

### ISSUE THREAD

**Issue by davidkhess** [vuetifyjs/docs#235]
This is useful for cases where the value of one field needs to be compared to the value of another. Full discussion here:

https://github.com/vuetifyjs/vuetify/issues/1826

**Comment by KaelWD** [comment]
Simple example, with comment about what *not* to do: https://codepen.io/anon/pen/xXgzRa?editors=1010

**Comment by KaelWD** [comment]
With Vue 2.5, you can use a lambda for data again as it now gets passed the vm instance as an argument.
