### ISSUE TITLE
how to open dialog by clicking a button outside

### ISSUE THREAD

**Issue by rashnk** [vuetifyjs/docs#238]
im not well understanding the doc.
why the button inside v-dialog ? 

```
<v-dialog v-model="dialog" persistent>
      <v-btn primary dark slot="activator">Open Dialog</v-btn>
```
 

how can i open a modal from my existing button ?

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
