### ISSUE TITLE
badges are found in directives instead of components

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/docs#261]
dev branch
![image](https://user-images.githubusercontent.com/15625235/31044050-cddc6cf4-a5f1-11e7-88b6-91ffe176036d.png)

**Comment by KaelWD** [comment]
If you click it you get sent to http://localhost:8080/#main-toolbar

**Comment by jacekkarczmarczyk** [comment]
It searched on live site
