### ISSUE TITLE
Example codes should come with all relevant code to reproduce carbon copy of the excepted outcome

### ISSUE THREAD

**Issue by Napzu** [vuetifyjs/docs#28]
I have tried to get grid component example working couple of times.

When I copy pasted to code to Codepen, included all the relevant files, I did't get anything near the outcome I was expecting.

I was guided by @mfferreira that:
- wrap whole thing with v-app, still not the same outcome
- initialize your Vue app, still not the same outcome
- add some CSS to make it same, finally same outcome that I was excepting

So although maybe some "mistakes" was made by my part, I think examples could and should be made better with all the relevant code to reproduce the outcome of the example. Full minimal example links to codepen, jsbin or other would be nice.

With complete examples, new Vuetify experimenters would get much better user experience, get started more quickly, and most importantly, put Vuetify to their toolchain because "it just works" that good and gives exactly the documented outcome everybody is expecting it to be.

I really like what you guys are doing and I want Vuetify to come default choice to all Vue developers to make Vue things even better!

Keep up the good work!

**Comment by Napzu** [comment]
Actually one more point. All the examples should mirror the default you get with just including all the files. Just using the HTML should get same results as the examples.

**Comment by itsjef** [comment]
You said exactly what a new user like me expect to get from the official document. We should be able to reproduce the given outcomes with ease just by following exactly what it gave us.

Getting:

![screenshot from 2017-04-28 16-06-33](https://cloud.githubusercontent.com/assets/1902587/25522317/ae679d06-2c2c-11e7-9184-48c11e1b8363.png)
@ https://codepen.io/itsjef/pen/JNWbZB

instead of the lovely, elegant, polished look:

![screenshot from 2017-04-28 16-04-29](https://cloud.githubusercontent.com/assets/1902587/25522232/653985a4-2c2c-11e7-9c12-212653194b14.png)

is is quite a _"The docs can't be wrong, isn't it? So why can't I make it like they did?"_-y experience :cry:

**Comment by Napzu** [comment]
The first impressions of Vuetify newcomers is; This looks super cool; I will try this now; This is not anything like the example; Maybe I have to wait another year it to mature; 

On Vue docs, when you first tried that, it worked like magic!

You have usually just on change to prove newcomer that "your magic sauce is better that the others".

I want this framework success that it would be defacto framework to go with Vue. And even though clearly, it is really success already, it would be even more success if documented examples "worker like Magic".

**Comment by mfferreira** [comment]
@Napzu Thank you for the kind feedback. You certainly mention a very valid point.
We're working towards improving the documentation, specially in the examples department.

**Comment by johnleider** [comment]
Completely agree, which is why the docs are being significantly updated.

**Comment by johnleider** [comment]
This is now the process in the next branch of the documentation. Every example is a self contained Vue template and will provide information on the template/script/style portions of every example.

**Comment by Napzu** [comment]
Great news! Thanks for the info.
