### ISSUE TITLE
how to use vee-validate with undeclared objects?

### ISSUE THREAD

**Issue by renatosistemasvc** [vuetifyjs/docs#287]
**Versions:**

VueJs: 2.4.2
Vee-Validate: 2.0.0-rc.18

**Description:**

I'm using vee-validate with vuetifyjs. I would like to use vee-validate with an object without having to declare properties.
how to use vee-validate with undeclared objects?

```
<v-text-field
:label="'Nome'"
:name="'username'"
v-model="dados.username"
:error-messages="errors.collect('username')"
v-validate="'required'"
data-vv-name="username"
required
></v-text-field>
```

```
 data() {
            return {
                dados: { } 
            };
},
```
It only works if I set the object's property this way:

```
 data() {
            return {
                dados: { username: ' ' } 
            };
},
```
I do not want to have to declare the username

**Comment by KaelWD** [comment]
You don't. Vue's reactivity requires all object properties to be initialised. 

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
