### ISSUE TITLE
Stepper documentation missing v-stepper-items tag

### ISSUE THREAD

**Issue by GMory** [vuetifyjs/docs#298]
# Steps to reproduce

Open https://vuetifyjs.com/components/steppers
View any of the examples

# Versions

Vuetify 0.16

# What is expected ?

According to the upgrade guide, you should:
> Wrap all v-stepper-content items with a single v-stepper-items component

So `v-stepper-items` should be present in both the documentation and the source.

# What is actually happening ?

`v-stepper-items` is missing from both the documentation and the source.

**Comment by jacekkarczmarczyk** [comment]
closed in #334
