### ISSUE TITLE
Update vee-validate examples

### ISSUE THREAD

**Issue by lobosan** [vuetifyjs/docs#300]
### Steps to reproduce
Use $validates: true to activate vee-validate

### Versions
vee-validate 2.0.0-rc.19

### What is expected ?
Do not show warning in chrome dev-tools

### What is actually happening ?
This warning appears 

> $validates option has been deprecated please set the $_veeValidate.validator option to "new" instead

### Possible solution
Replace `$validates: true` with
```
$_veeValidate: {
    validator: 'new'
}
```

### Additional feature
If possible also show how to customize error messages and attributes through the dictionary property like this inside the $_veeValidate object:
```
dictionary: {
  es: {
    attributes: {
      contrasena: 'Contraseña'
    },
    custom: {
      telefonoFijo: {
        regex: 'El formato no corresponde al Ej. 022585623 ext 123456'
      },
      telefonoCelular: {
        regex: 'El formato no corresponde al Ej. 0983507946'
      }
    }
  }
}
```

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetifyjs.com/pull/171
