### ISSUE TITLE
Using vee-validate with different scopes????

### ISSUE THREAD

**Issue by renatosistemasvc** [vuetifyjs/docs#307]
How do I validate different scopes inside a template using vee-validate? 
example:

```
<template>
    <div>
        <form data-vv-scope="form1">
            <v-layout row wrap>
                <v-flex xs12 class="py-0">
                        <v-text-field label="test1" v-model="test1" v-validate="'required'" data-vv-name="test1" :error-messages="errors.collect('test1')" required></v-text-field>
                </v-flex>
            </v-layout>
            <v-btn color="primary" flat @click.native="submit('form1')">submit1</v-btn>
        </form>
        
        <form data-vv-scope="form2">
            <v-layout row wrap>
                <v-flex xs12 class="py-0">
                        <v-text-field label="test2" v-model="test2" v-validate="'required'" data-vv-name="test2" :error-messages="errors.collect('test2')" required></v-text-field>
                </v-flex>
            </v-layout>
            <v-btn color="primary" flat @click.native="submit('form2')">submit2</v-btn>
        </form>
    </div>
</template>
```

```
methods:{
        submit(scope) {

            this.$validator.validateAll(scope).then((result) => {
                     console.log(result);
            });

        }
}
```
Is there any way to validate different forms within a same template?
I apologize if this is not the best place to ask, but there are days I'm trying to make it work.

**Comment by nekosaur** [comment]
This issues board is only for bugs and feature requests for the current documentation. If you have questions regarding Vuetify, please join us in chat instead at https://chat.vuetifyjs.com. That said, this sounds like purely a question regarding vee-validate, so you might get a better response through their support channels.

**Comment by renatosistemasvc** [comment]
thank you!!

**Comment by janein** [comment]
@renatosistemasvc did you find a way to get this working?

**Comment by renatosistemasvc** [comment]
@janein, no.
I decided to change the validation for basic validation of vuetifyjs.
I realized that it is much simpler and cleaner to work with it instead of Vuelidate.

**Comment by janein** [comment]
@renatosistemasvc thanks for the tip - I think I'll go with this solutions as well.

**Comment by nassimBo55** [comment]
Hi there, maybe this is not the best place to ask / open vee-validate issue. Probably here https://github.com/baianat/vee-validate/issues is the best place to do so. Anyway check out this vee-validate documentation regarding scope behavior: 
http://vee-validate.logaretm.com/examples#scope-example

**Comment by janein** [comment]
Thanks, but I already checked all vee-resources before and couldn't find a solution fitting my scenario.
Tried it with vuetify's `<v-form>` and now it works just fine!
