### ISSUE TITLE
Pagination on Tabs

### ISSUE THREAD

**Issue by adivity** [vuetifyjs/docs#349]
Is Tabs Pagination still supported? The Right/Left chevron isn't displaying correctly for me. It shows on some browser sizes, but not others. 

See: https://image.prntscr.com/image/eym2UFFdSGO604tYnfjtuw.png

Tested on Desktop - Firefox / Chrome . On mobile, scroll works, but no chevron

**Comment by KaelWD** [comment]
It's material spec https://material.io/guidelines/components/tabs.html

The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

**Comment by adivity** [comment]
I am reporting a bug :(

**Comment by nekosaur** [comment]
Then it should be reported on the vuetify repo, using the provided template.

As @KaelWD pointed out, tabs follow the spec defined at https://material.io/guidelines/components/tabs.html. When it gets to mobile browser sizes, chevrons do not appear and instead swiping is enabled.
