### ISSUE TITLE
Buttons to copy vue-cli init don't do anything

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vuetifyjs/docs#357]
In Chrome 63 on Mac OS, the vue-cli init strings aren't shown anywhere when you click one (NUXT or Webpack Advanced, for example). There's a button (the tooltip says "Copy markup, by the way" - but when you click it, it doesn't actually copy the string. 
Right now, you'd have to click through to the template's github repo and copy the string out of the Readme.

**Comment by zvory** [comment]
Possibly similar:

When I got https://vuetifyjs.com/components/data-tables and click "view source" on one of the cards, then click the copy to clipboard icon, it doesn't do anything.

Ubuntu 17.10 Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by KaelWD** [comment]
I fixed this ages ago (85be2056d1714fb79bf7b8b875ab777655c30a72), looks like it was never deployed though. I'll push it up when I get home unless someone else beats me to it.

**Comment by zvory** [comment]
Thanks mate 👍
