### ISSUE TITLE
v-date-picker and v-checkbox

### ISSUE THREAD

**Issue by mclaran** [vuetifyjs/docs#359]
Hello! How to put a custom icon?
![image](https://user-images.githubusercontent.com/22270702/32324880-6401097a-bfff-11e7-98e5-8b17e4365f8f.png)

The same is in checkbox

![image](https://user-images.githubusercontent.com/22270702/32324979-ba8a8564-bfff-11e7-8a9d-49194081a76e.png)

vuetify v0.15.7, v0.16.9, v0.17.0-beta.1

**Comment by KaelWD** [comment]
You need to install the material icons font.

**Comment by mclaran** [comment]
I use font avesome. the documentation says that it is supported. in other cosponsents there is a method for specifying icons. The checkbox also exists, but does not work. there is no data-picker

**Comment by KaelWD** [comment]
THis is the wrong repo for this issue anyway. See vuetifyjs/vuetify#2123
