### ISSUE TITLE
Masked text-field validation

### ISSUE THREAD

**Issue by coeneivan** [vuetifyjs/docs#363]
Hi

I was wondering if there is a way to validate the mask. 
If the content isn't filled to the last character, it should throw an error

I'm using it as follow:
```html
<v-text-field label="Number" mask="A-######" v-model="number" :rules="nrRules" required>
</v-text-field>
```

For the moment i'll just count the characters in my model.

Thanks for all the awesomeness you give me!

**Comment by coeneivan** [comment]
I see that my rules aren't working if I have a mask...

I have the following rules:

```js
nrRules: [
        (v) => !!v || 'Number is required',
        (v) => v && v.length != 8 || 'Number must be 8 characters (P- or I- incl)'
      ]
```

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

**Comment by coeneivan** [comment]
Ow, okey.

I'll post it there. 

Thanks
