### ISSUE TITLE
v-table-data width 

### ISSUE THREAD

**Issue by YouriBeketov** [vuetifyjs/docs#377]
It is my understanding that the 0.17 release was supposed contain a f() to control the widths of the table headers and rows. 

It doesn't seem to be working. I tried with' %' and 'px'. 

https://codepen.io/YuraB/pen/qVXegp

It is my first codepen, I hope it works correctly

**Comment by KaelWD** [comment]
This is the wrong repo for this issue. Please submit it to the main issue board using this template: https://issues.vuetifyjs.com/
