### ISSUE TITLE
[Request] v-card-media responsive

### ISSUE THREAD

**Issue by Imanullah** [vuetifyjs/docs#389]
Anyone` could help me how to v-card-media image responsive 

`<v-card-media` src="...." `height="280px"></v-card-media>`
we need dynamic height when scale down 
ex:
`<v-card-media` src="imgUrl" height-lg="280px" height-md="200px" `height-xs="100px"></v-card-media>`

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
