### ISSUE TITLE
Props undefined error on rendering v-data-table using typescript

### ISSUE THREAD

**Issue by jayalakshmis** [vuetifyjs/docs#418]
Pardon beginner's ignorance. Am trying to render Vuetify's data table with data being populated in a typescript file as seen below. Upon emulating what is provided in the sample doc [here][1], I encounter the following error

> vue.runtime.esm.js?a427:475 [Vue warn]: Property or method "props" is
> not defined on the instance but referenced during render. Make sure to
> declare reactive data properties in the data option.

**data.vue**

    <template>
        <v-content>
            <v-data-table
            v-bind:headers="headers"
            :items="items"
            class="elevation-1"
            hide-actions
            dark
          >
          <template slot="items" slot-scope="props">
            <td>{{ props.item.name }}</td>
            <td class="text-xs-right">{{ props.item.calories }}</td>
            <td class="text-xs-right">{{ props.item.fat }}</td>
            <td class="text-xs-right">{{ props.item.carbs }}</td>
            <td class="text-xs-right">{{ props.item.protein }}</td>
            <td class="text-xs-right">{{ props.item.sodium }}</td>
            <td class="text-xs-right">{{ props.item.calcium }}</td>
            <td class="text-xs-right">{{ props.item.iron }}</td>
          </template>
            </v-data-table>
        </v-content>
    </template>

**Ts file**

    import Vue from "vue";
    import { Component } from "vue-property-decorator";
    let template = require("./data.vue");
    
    @Component({
        mixins: [template],
    })
    export default class Inventory extends Vue {
        get tmp() {
            return "";
        }
        get search() { return ""; }
        get pagination() { return {}; }
        get headers() {
            return [
                {
                    text: "Dessert (100g serving)",
                    align: "left",
                    sortable: false,
                    value: "name"
                },
                { text: "Calories", value: "calories" },
                { text: "Fat (g)", value: "fat" },
                { text: "Carbs (g)", value: "carbs" },
                { text: "Protein (g)", value: "protein" },
                { text: "Sodium (mg)", value: "sodium" },
                { text: "Calcium (%)", value: "calcium" },
                { text: "Iron (%)", value: "iron" }
            ];
        }
        get items() {
            return [
                {
                    value: false,
                    name: "Frozen Yogurt",
                    calories: 159,
                    fat: 6.0,
                    carbs: 24,
                    protein: 4.0,
                    sodium: 87,
                    calcium: "14%",
                    iron: "1%"
                },
                {
                    value: false,
                    name: "Ice cream sandwich",
                    calories: 237,
                    fat: 9.0,
                    carbs: 37,
                    protein: 4.3,
                    sodium: 129,
                    calcium: "8%",
                    iron: "1%"
                }
            ];
        }
    }

Is there something that am missing to wire up the data?

**Packages**
  `"vue": "2.4.2",`
  `"vuetify": "^0.17.6",`
`dev dependencies:
  "typescript": "^2.4.1",
`

*Also I dont see a reason to use props here as there isnt any parent child component relationship unless the props that is being used here refers to something else*

  [1]: https://vuetifyjs.com/components/data-tables#standard

**Comment by KaelWD** [comment]
Vuetify 0.17 requires Vue 2.5

This is also the wrong repo for this issue, and in fact shouldn't even *be* an issue as it is a problem specific to your project. We prefer that these questions be asked on discord: https://chat.vuetifyjs.com
