### ISSUE TITLE
v-app documentation is missing

### ISSUE THREAD

**Issue by cropr** [vuetifyjs/docs#420]
There is no description of v-app component.  Although it is mentioned that it is required, there is no api section with properties, slots, ....

**Comment by KaelWD** [comment]
This repository is **deprecated**
The current documentation is now at https://github.com/vuetifyjs/vuetifyjs.com

Framework issues should be reported with https://issues.vuetifyjs.com  
Documentation-specific issues should be reported on https://github.com/vuetifyjs/vuetifyjs.com
