### ISSUE TITLE
0.16 documentation is broken

### ISSUE THREAD

**Issue by DCzajkowski** [vuetifyjs/docs#421]
You cannot preview source-code of any component in 0.16 version of the documentation, because every source code 404's.

**How to reproduce:**
Navigate to: https://vuetifyjs.com/releases/0.16/#/components/text-fields
and open your dev tools. Everything 404s.

**Comment by KaelWD** [comment]
This repository is **deprecated**
The current documentation is now at https://github.com/vuetifyjs/vuetifyjs.com

Framework issues should be reported with https://issues.vuetifyjs.com  
Documentation-specific issues should be reported on https://github.com/vuetifyjs/vuetifyjs.com
