### ISSUE TITLE
Better documentation for css helper classes.

### ISSUE THREAD

**Issue by jaesung2061** [vuetifyjs/docs#422]
Many css classes like `align-{start|end}` and `justify-{start|end}` should be documented in it's own "css helpers" page on the docs. I'm tired of digging through the source to find these things.

**Comment by KaelWD** [comment]
This repository is **deprecated**
The current documentation is now at https://github.com/vuetifyjs/vuetifyjs.com

Framework issues should be reported with https://issues.vuetifyjs.com  
Documentation-specific issues should be reported on https://github.com/vuetifyjs/vuetifyjs.com
