### ISSUE TITLE
Add items example, item-value and item-text to Select docs

### ISSUE THREAD

**Issue by VitorLuizC** [vuetifyjs/docs#48]
I've tried all day long to figure out how to use `v-select` component. Without success all items are showed, instead of a single one, after selecting an item.

![Screencast of this error](https://gyazo.com/3a217782ca8912888558f1218dcf8d03.git)

Docs only explain about `text` property on `items`, nothing about `value`.

![Screenshot of the text property part on docs](https://cloud.githubusercontent.com/assets/9027363/26003682/c1d1d0c2-3709-11e7-866b-5a32c557c444.png)

After some source i've found an exemple with `value` property on items and using `item-text` and though if there's also an `item-value` on API. Yeap, it does. Vuetify is much complete, but it should be included on docs with an example of items array.

**Comment by johnleider** [comment]
Done.
