### ISSUE TITLE
Possibility to archive older versions of the docs?

### ISSUE THREAD

**Issue by ThomasG77** [vuetifyjs/docs#53]
Thanks for the release of the 0.12x

This new release also also brings the issue of versioning or at least freeze old documentation build like 0.11.1.
When a developer did not already upgrade to current Vuetify library, he has to manage the old way of doing for weeks using old code before upgrading.
You can always build the docs from the repo but it's not really practical.

To way to solve this would be:

- the simpler: built documentation could be attached/stored as a standalone zip file in https://github.com/vuetifyjs/docs/releases
- the more complex: manage the versioning in the URL e.g https://vuetifyjs.com/vuetify/v0.12/quick-start, https://vuetifyjs.com/vuetify/v0.11.1/quick-start,...

**Comment by ThomasG77** [comment]
Related to #44 so feel free to keep this issue opened or to already close it.

**Comment by johnleider** [comment]
It should stay open. I need to implement doc versioning. The rework released today set the foundation for it to happen though.

**Comment by johnleider** [comment]
This has been added and will be part of the next release!
