### ISSUE TITLE
<v-text-field label> doesn't render correctly above the input

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/docs#57]
Instead it overlaps the input area. Sample:

          <v-stepper-content step="1">
            <v-card class="secondary elevation-0 mb-3">
              <v-card-text>
                <v-container fluid>
                  <v-layout row-sm wrap column child-flex-sm>
                    <v-flex xs4>
                      <v-subheader class="grey--text text--lighten-1" v-tooltip:bottom="{ html: 'This is the tooltip' }">Subheader:</v-subheader>
                    </v-flex>
                    <v-flex xs8>
                      <v-text-field
                        v-model="test"
                        prefix="prefix"
                        label="This label should be at the top of the component"
                        hint="This is a hint"
                        single-line
                        light
                        counter
                        min="16"
                        max="16"
                        maxlength="16"
                        placeholder="placeholder"
                      ></v-text-field>
                    </v-flex>
                  </v-layout>
                </v-container>
              </v-card-text>
            </v-card>
          </v-stepper-content>

**Comment by johnleider** [comment]
Could you tell me which example you are referencing?

**Comment by azaars** [comment]
Wow, that's a quick reply. I really appreciate it.

I was kinda mixing things from a number of example files. I've emailed the screenshot of what appears on the screen together with the complete .vue . Please have a look.

**Comment by johnleider** [comment]
Does this issue still happen?

**Comment by azaars** [comment]
I tried with almost all props of `<v-text-field>` in one go and later found out that `single-line` didn't play well with `label`. Removing `single-line` fixed the problem. Thank you.
