### ISSUE TITLE
<v-stepper> is dark in dark theme

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/docs#58]
It's all dark. Also the text in <v-stepper-step> remains black and can't be changed easily. Workaround: Wrap with <v-card class="grey">.

vuetifyjs really rocks!! Great work @johnleider and thank you so much.

**Comment by johnleider** [comment]
Screen shot, location, or something that can show this?

**Comment by azaars** [comment]
The subsequent release fixed this. I think it was v0.12.3, I forgot. Thank you.
