### ISSUE TITLE
Scroll stops working after opening full screen modal

### ISSUE THREAD

**Issue by lukaszb** [vuetifyjs/docs#80]
Steps to reproduce:

- go to [Dialogs docs page](https://vuetifyjs.com/components/dialogs)
- click on "Open dialog" button at Fullscreen example (scroll bar already disappeared)
- close modal (by either clicking on save or close button)
- user can no longer scroll vertically

See a movie: http://tmpmemos.s3.amazonaws.com/vuetify-docs-scroll-issue.mp4

After briefly scanning through the code it looks like scroll bar is not restored here: https://github.com/vuetifyjs/vuetify/blob/master/src/components/dialogs/Dialog.js#L57. It's a blind shot, though.

**Comment by johnleider** [comment]
This has been fixed on the main repo.
