### ISSUE TITLE
The components Edit link get 404

### ISSUE THREAD

**Issue by wilsonwu** [vuetifyjs/docs#81]
The Edit link in each component get 404:
In file:
components/ComponentView.vue

Current is:
v-bind:href="'https://github.com/vuetifyjs/docs/tree/master/src/pages/'+doc.edit+'.vue'"

Should be:
v-bind:href="'https://github.com/vuetifyjs/docs/blob/master/pages/'+doc.edit+'.vue'"

**Comment by pfuhrmann** [comment]
Fixing here https://github.com/vuetifyjs/docs/pull/83

**Comment by johnleider** [comment]
This has already been fixed on dev, silly mistake, thank you!
