### ISSUE TITLE
feature request: allow canvas in modal windows

### ISSUE THREAD

**Issue by Dmitry1987** [vuetifyjs/docs#95]
Hello,
first, thank you for this UI library, it is awesome!

I tried to show chartjs graph in a modal window, but it was not displayed:

![image](https://user-images.githubusercontent.com/9369080/27751643-f70956f4-5de5-11e7-920a-63385354e604.png)

despite I see it rendered in html:
![image](https://user-images.githubusercontent.com/9369080/27751683-1b9a360a-5de6-11e7-8e57-6877b6342eec.png)

somehow the fact it's shown in modal window, breaks the canvas. (when i move it outside, it works ok on the page itself)

I want to ask is it a limitation of current modals component and it can be extended/fixed? or it's a limitation of browsers themselves?

If it's possible to make modals show canvas properly - please point me in the right direction and I'll submit a PR (if this functionality is good to have in this library?)

thanks!

**Comment by johnleider** [comment]
This would be an issue for the main repository, not the documentation. Can you please repost this there? Thank you.

**Comment by Dmitry1987** [comment]
Hi, I saw it says 'don't create ticket if it's related only to your specific edge cases' , and I guess not many people would need a canvas in modal...  
for now I solved it with creating my own modal from standart vue example. 

thanks :)
