### ISSUE TITLE
`menu__content` class z-index issue

### ISSUE THREAD

**Issue by mogita** [vuetifyjs/docs#98]
I'm browsing the demo, found a z-index issue on the dropdown menu, I saw it [here](https://vuetifyjs.com/components/dialogs) in the `#4 Form` section. Please take a look at the image attached.

The issue happens in both latest public versions of Chrome and Safari (OS X 10.11.6).

![screenshot 2017-07-04 10 56 20](https://user-images.githubusercontent.com/1173069/27813349-d73e0df0-60a7-11e7-9ceb-9e1cd3b5c598.png)

**Comment by johnleider** [comment]
This has been fixed with the latest release.
